---
- name: "Playing with Ansible from a downloaded playbook"
  hosts: localhost
  connection: local
  tasks:

    - name: "just execute a ls -alrt command"
      shell: "ls -alrt"
      register: result

    - name: "Print environment variable"
      debug:
        var: result.stdout_lines

    - name: "install stuff"
      package:
        name: "{{ item }}"
        state: present
      loop:
        - tree
        - yamllint
